name: RFC Weekly Newletter

on:
  schedule:
    - cron: '0 15 * * 1'
  repository_dispatch:
    types: [manual_trigger]

jobs:
  send_newsletter:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_S3_BUCKET: github-action-cache
      RFCWEEKLY_SENDGRID_FROM_ADDRESS: ${{ secrets.RFCWEEKLY_SENDGRID_FROM_ADDRESS }}
      RFCWEEKLY_SENDGRID_TO_ADDRESS: ${{ secrets.RFCWEEKLY_SENDGRID_TO_ADDRESS }}
      RFCWEEKLY_SENDGRID_GROUP: ${{ secrets.RFCWEEKLY_SENDGRID_GROUP }}
      RFCWEEKLY_SENDGRID_TEMPLATE_ID: ${{ secrets.RFCWEEKLY_SENDGRID_TEMPLATE_ID }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rfcweekly/requirements.txt
      - run: mkdir rfcweekly/.cache
      - name: Download cache
        run: aws s3 cp s3://$AWS_S3_BUCKET/rfcweekly/ rfcweekly/.cache/ --recursive
      - name: Fetch RFCs and Send Emails
        working-directory: rfcweekly
        run: python run.py
      - name: Refresh cache
        run: aws s3 cp rfcweekly/.cache/ s3://$AWS_S3_BUCKET/rfcweekly/ --recursive
      - name: Commit and push if it changed
        run: |-
          timestamp=$(date -u)
          echo ${timestamp} > rfcweekly/HEARTBEAT
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
