name: RFC Weekly Newletter
on:
  repository_dispatch:
    types: [manual_trigger]
jobs:
  send_newsletter:
    runs_on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r rfcweekly/requirements.txt
    - run: mkdir .cache
    - name: Download cache
      run: s3 cp -r s3://$S3_BUCKET/rfcweekly/cache rfcweekly/.cache/
    - name: Fetch RFCs and Send Emails
      working-directory: rfcweekly
      run: python run.py
    - name: Refresh cache
      run: s3 cp -r rfcweekly/.cache s3://$S3_BUCKET/rfcweekly/cache
