name: RFC Weekly Newletter
on:
  repository_dispatch:
    types: [manual_trigger]
jobs:
  send_newsletter:
    runs_on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_S3_BUCKET: github-action-cache
      RFCWEEKLY_SENDGRID_FROM_ADDRESS: ${{ secrets.RFCWEEKLY_SENDGRID_FROM_ADDRESS }}
      RFCWEEKLY_SENDGRID_GROUP: ${{ secrets.RFCWEEKLY_SENDGRID_GROUP }}
      RFCWEEKLY_SENDGRID_TEMPLATE_ID: ${{ secrets.RFCWEEKLY_SENDGRID_TEMPLATE_ID }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rfcweekly/requirements.txt
      - run: mkdir .cache
      - name: Download cache
        run: aws s3 cp -r s3://$AWS_S3_BUCKET/rfcweekly/ rfcweekly/.cache/
      - name: Fetch RFCs and Send Emails
        working-directory: rfcweekly
        run: python run.py
      - name: Refresh cache
        run: aws s3 cp -r rfcweekly/.cache/* s3://$AWS_S3_BUCKET/rfcweekly/
